# Generated by Django 4.0.6 on 2022-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarypage',
            name='example_file',
            field=models.FileField(upload_to='examples'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='library_file',
            field=models.FileField(upload_to='libraries'),
        ),
    ]
