# Generated by Django 4.0.6 on 2022-08-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarys', '0004_commentreaction_author_commentreaction_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
