# Generated by Django 4.0.6 on 2022-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarys', '0005_alter_commentreaction_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='like',
        ),
        migrations.AddField(
            model_name='librarypage',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='librarypage',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
